name: Cloudflare Production Deployment
on:
  push:
    branches:
      - main
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      #- name: Install deps
      #  run: sudo apt-get install -y libkrb5-dev
      - name: Install
        run: yarn install
      #- name: Install provider
      #  run: cd drd-fsprovider && yarn install
      #- name: Build
      #  run: yarn build
      #- name: Copy files into final directory
      #  run: yarn prepare-start
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
