name: Cloudflare Preview Deployment
on:
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install
        run: npm install
      - name: Install provider
        run: cd drd-fs && npm install
      - name: Build
        run: npm run build
      - name: Copy files into final directory
        run: npm run prepare-start
