name: Cloudflare Preview Deployment
on:
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Install
        run: yarn install
      - name: Install provider
        run: cd drd-fsprovider && yarn install
      - name: Build
        run: yarn build
      - name: Copy files into final directory
        run: yarn prepare-start
