name: Cloudflare Preview Deployment
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install deps
        run: sudo apt-get install -y libkrb5-dev g++ gcc make pkg-config libx11-dev libxkbfile-dev libsecret-1-dev
      - name: Install
        run: npm install
      - name: Install provider
        run: cd drd-fs && npm install
      - name: Build
        run: npm run build
      - name: Copy files into final directory
        run: npm run prepare-start
      - name: Deploy
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: versions upload --preview-alias pr-${{ github.event.number }}
      - name: 📬 Update deployment status
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          append: true
          # Only `deployment-url` is available
          message: |
            | ${{ matrix.name }} | ${{ steps.deploy.outputs.deployment-url }} |
